image: node:latest

before_script:
    - "npm install node-sass snoowrap"

cache:
    paths:
    - node_modules/

publish:
    stage: deploy
    environment:
        name: production
    script:
        - "npx node-sass --output-style compressed --include-path ./ ./main.scss ./main.css"
        - "node -e \"new (require('snoowrap'))(${CONFIG}).getSubreddit('DevWars').updateStylesheet({css: require('fs').readFileSync('./main.css', 'utf8'), reason: 'GitHub push'});\""
