image: node:latest

before_script:
    - "npm install node-sass snoowrap"

publish:
    stage: deploy
    environment:
        name: production
    script:
        - "node-sass --output-style compressed --include-path ./ ./main.scss ./main.css"
        - "node -e \"new (require('snoowrap'))(${CONFIG}).getSubreddit('DevWars').updateStylesheet({css: `cat ./main.css`, reason: 'GitHub push'});\""
