image: node:latest

before_script:
    - "npm install node-sass snoowrap"

cache:
    paths:
    - node_modules/

publish:
    stage: deploy
    environment:
        name: production
    script:
        - >-
            npx node-sass --output-style compressed --include-path ./ ./main.scss | sed -e 's/\/\*!/\/\*/g' > ./main.css
        - >-
            node -e "new (require('snoowrap'))(${CONFIG}).getSubreddit('DevWars').updateStylesheet({css: require('fs').readFileSync('./main.css', 'utf8').trim(), reason: 'GitHub push'}).then(()=>{process.exit(0);}).catch(()=>{process.exit(1);});"
